let movies = {
  "Totoro" : {
    illustration : {
      title : "Mon voisin Totoro",
      path: "/photos/totoro.jpg",
    },
    content1 : {
      text : `Tatsuo Kusakabe, jeune anthropologue et professeur non titulaire d'une université de Tokyo, arrive dans le village où il va emménager avec ses deux filles, Satsuki, dix ans, et Mei, quatre ans. Les petites découvrent joyeusement leur nouvelle maison, qui n’a pas été habitée depuis un certain temps, et la campagne environnante où trône un camphrier gigantesque. Explorant l’habitation, de style japonais, elles trouvent des glands qui tombent de la soupente et une pièce remplie de petites créatures noires qui s’éclipsent (les susuwatari) ; leur père leur explique qu’il s’agit de noiraudes. Elles montent peu rassurées à l’étage, et Mei, qui attrape une des créatures, se retrouve les mains pleines de suie. Redescendant, elles rencontrent leur nouvelle voisine venue aider à faire le ménage, une grand-mère, qui leur explique que les noiraudes emménagent dans les lieux inhabités et partiront bientôt. Satsuki est polie et accueillante, mais Mei a peur de la nouvelle venue, et se cache derrière sa sœur. Alors qu’ils s’activent tous pour réactiver la pompe, nettoyer les salles de vie et déballer les affaires, Kanta, le petit-fils de la vieille dame, âgé lui aussi d’une dizaine d’années, apporte un paquet de la part de sa mère et dit à sa jeune voisine que leur nouvelle maison est hantée, avant de partir en courant.

      Le soir venu, de fortes rafales de vent font trembler la maison ; dans le bain, Tatsuo et ses filles rient fort pour chasser les fantômes, tandis que les noiraudes quittent la maison et émigrent vers le grand arbre. Le lendemain matin, ils font la lessive au lavoir, puis partent à vélo le long des rizières où leurs voisins s’activent, pour passer la journée avec Yasuko, la mère des petites, hospitalisée à proximité. Ils passent devant Kanta, qui échange des grimaces avec Satsuki.
      
      À la fin des vacances, Satsuki reprend l’école après avoir préparé le repas de midi pour sa sœur et son père ; ce dernier se met au travail à son bureau, tandis que Mei vagabonde à l’extérieur. Trouvant un gland, la petite fille le ramasse, et en voit plusieurs autres formant une piste ; la suivant, elle voit passer devant elle un petit être blanc-translucide et le poursuit, mais celui-ci se cache sous la maison. Alors que la fillette surveille une cavité, la petite créature, accompagnée maintenant par une autre un peu plus grande transportant un sac de glands, s’éclipse par une autre sortie, mais entendant des glands tomber, Mei les repère et les poursuit à nouveau. Continuant leur route à travers un étroit chemin de végétation, puis dans la forêt, tous trois aboutissent au pied du grand camphrier entouré d’un shimenawa, et les deux êtres disparaissent dans un trou entre les racines. Y tombant à leur suite, la petite fille découvre le domaine de Totoro, sorte de créature de la taille d’un ours au cri impressionnant, avec qui elle fait connaissance, avant de s’endormir sur son ventre.
      
      Le midi, Satsuki revient de l’école et cherche Mei ; elle trouve son chapeau devant la trouée et trouve sa sœur endormie non loin. À son réveil, celle-ci lui raconte sa rencontre avec Totoro ; Tatsuo les rejoint et ils poursuivent le long du chemin sous les branches, mais aboutissent sur leur maison. La petite fille est déconcertée, et son père lui explique qu’elle a dû voir le maître de la forêt ; ils vont tous trois à travers celle-ci pour voir le grand arbre, mais Mei ne retrouve pas l’entrée de l’antre de la créature. Après avoir salué le camphrier, qui est la raison pour laquelle Tatsuo a choisi d’habiter ce village, ils repartent.
      
      Le lendemain, Satsuki confie Mei à leur voisine avant d’aller à l’école pour la journée, et est surprise de voir la vieille dame arriver avec la petite fille alors qu’elle a encore deux heures de cours. Mei tenant à être avec sa grande sœur, elle est accueillie dans la classe avec des crayons, et dessine Totoro. Le soir venu, les deux fillettes reprennent le chemin de leur maison, mais une pluie torrentielle se met à tomber et elles doivent se réfugier dans l’abri d’une divinité shinto ; Kanta passe avec un vieux parapluie qu’il laisse à Satsuki avant de rentrer chez lui en courant. Après être rentrées chez elles, les deux fillettes partent à la rencontre de leur père avec un parapluie, et passent chez leurs voisins rendre celui que Kanta leur a prêté ; elles sont accueillies par la mère du garçon, qui timide reste caché tout en manifestant sa joie et sa fierté d’avoir aidé Satsuki. `,
      images : "/photos/totoro3.jpg",
    },
    content2 : {
      text : `Les deux fillettes attendent à l’arrêt de bus sous la pluie, mais ce dernier a du retard ; Satsuki prend Mei qui s’endort sur son dos et patiente, quand soudain, elle voit Totoro arriver et attendre à côté d’elle. Pour se protéger de la pluie, la créature n’a qu’une large feuille sur la tête qui lui goutte sur le nez, et la jeune fille lui prête le parapluie qu’elle a apporté pour son père ; le maître de la forêt est étonné, mais ravi d’entendre le bruit des grosses gouttes qui, s’accumulant sur les feuilles des arbres, tombent sur l’objet. Alors que la pluie s’est arrêtée et que Mei se réveille, un « chat-bus (en) » arrive, et Totoro monte dedans après avoir donné un cadeau aux fillettes. Finalement, le bus arrive, et Tatsuo s’excuse d’être en retard ; ses filles expriment leur enthousiasme d’avoir vu les créatures, et ils rentrent joyeusement.

      Dans une lettre à sa mère, Satsuki décrit le cadeau de Totoro, un ensemble de graines emballées dans des feuilles de bambou, qu’elles ont planté dans le jardin, mais les jours passent et Mei s’impatiente de les voir pousser. Une nuit, les fillettes entendent des percussions et voient la famille Totoro danser autour de leur potager ; elles courent rejoindre les créatures, et voient émerveillées des pousses sortir de terre et grandir à vue d’œil pour devenir un amas d’arbustes luxuriants qui fusionnent pour donner un arbre géant, dont la ramure recouvre la maison. Totoro fait tourner une toupie magique sur laquelle il grimpe, et emmène Satsuki et Mei, accrochées sur son ventre, faire des acrobaties aériennes au-dessus de la campagne, avant de jouer de l’ocarina au sommet de l’arbre.
      
      Le lendemain, l’arbre a disparu ; pensant avoir rêvé, Mei et Satsuki se précipitent vers le potager et découvrent avec joie que les graines ont germé. Les fillettes aident leur vieille voisine à ramasser les légumes dans les champs et parlent du passage prochain de leur maman pour le week-end, lorsque Kanta apporte un télégramme issu de l’hôpital demandant d’appeler. Très inquiètes, elles courent avec leur jeune voisin vers la maison de celui-ci pour appeler leur père, et la nouvelle tombe comme un couperet : Yasuko est souffrante et ne pourra finalement pas venir. Terriblement déçue, Mei fait un caprice, et les deux sœurs se disputent ; Tatsuo part voir son épouse à l’hôpital, laissant ses filles sous la garde de la voisine, qui tente de rassurer et consoler Satsuki, terrifiée à l’idée que sa mère puisse mourir.
      
      Mei profite d’un moment d’inattention de la vieille femme pour partir seule apporter un épi de maïs à l’hôpital, mais celui-ci est à trois heures de route à pied. Constatant la disparition de la petite, Satsuki et la voisine s’affolent ; la jeune fille part sur le chemin de l’hôpital en interrogeant toutes les personnes qu’elle croise, lorsqu’elle voit Kanta arriver à vélo ; celui-ci lui propose d’aller à l’hôpital, tandis qu’elle retournera à l’étang où une sandalette a été retrouvée, et où tout le village recherche Mei. Elle part en courant et arrive essoufflée au plan d’eau, pour s’apercevoir soulagée que la chaussure n’est pas celle de sa sœur. La nuit va bientôt tomber, et les villageois s’activent pour rechercher la petite fille, tandis que Satsuki court à la trouée et prie pour que cette dernière la mène à Totoro ; se précipitant dans le passage, envahi de noiraudes, elle finit par trébucher et tomber en contrebas sur le ventre de la créature endormie. La jeune fille réveille le maître de la forêt et lui explique que Mei a disparu, avant de s’effondrer en larmes. Totoro la prend dans ses bras, lui sourit, et emplit ses poumons d’air pour s’envoler ; il court au sommet de son arbre, d’où il pousse un énorme rugissement pour faire venir le chat-bus, dans lequel Satsuki monte. La créature affiche « MEI » comme direction sur son panneau d’affichage et part en trombe ; passant à travers la forêt et les rizières, ils montent finalement sur une ligne de haute tension qu’ils suivent pour retrouver enfin la petite fille perdue.
      
      Le chat propose à Mei et Satsuki de les emmener à l’hôpital où, du haut d’un arbre, elles voient à travers la fenêtre leurs parents discuter ; finalement, Yasuko n’avait attrapé qu’un rhume sans gravité et ne tardera pas à rentrer à la maison. Les fillettes déposent l’épi de maïs sur lequel est gravé « pour maman » sur le rebord de la fenêtre, où Tatsuo le découvre, avant de repartir dans la nuit à bord du chat-bus qui les laisse chez elles. Mei se précipite dans les bras de la vieille voisine qu’elle a enfin adoptée, tandis que Satsuki discute joyeusement avec Kanta, devenu son ami ; au sommet de son arbre, Totoro joue tranquillement de l’ocarina, tenant toujours son parapluie ouvert malgré l’absence de pluie. Dans la première image du générique, un taxi ramène Yasuko à la maison où ses deux filles l’accueillent joyeusement ; les images suivantes laissent supposer qu’un petit frère est venu agrandir la famille qui s’est parfaitement intégrée dans son nouvel environnement. `,
      images :  "/photos/totoro4.jpg",
    },
    video : {
      srcVideo : "https://www.youtube.com/embed/jD-6_0h4KwM"
    }
  },

  "Chihiro" : {
    illustration : {
      title : "Le voyage de Chihiro",
      path: "/photos/Chihiro6.jpeg",
    },
    content1 : {
      text : `Chihiro Ogino (荻野 千尋, Ogino Chihiro), dix ans, boude à l’arrière de la voiture de ses parents1 ; ces derniers ont décidé de déménager à la campagne, et la petite fille regrette son ancienne école. En cherchant à rejoindre leur nouvelle maison, ils se perdent au bout d’une route tortueuse et arrivent devant un tunnel. Le traversant, malgré la réticence de Chihiro effrayée, ils arrivent dans ce qu’ils pensent être un parc à thèmes abandonné. Sentant une odeur de nourriture, ils rejoignent une échoppe vide regorgeant de victuailles, et les parents de la fillette s’installent ; prévoyant de payer en partant, ils commencent à manger goulûment. Agacée par leur comportement, Chihiro part explorer le village abandonné et se retrouve à l’entrée d’un pont menant à un palais des bains. Là, un jeune garçon l’avertit de partir vite avant le coucher du soleil.

      Alors que la nuit tombe rapidement, Chihiro se précipite pour retrouver ses parents, mais découvre avec horreur que ceux-ci se sont transformés en cochons. De plus en plus affolée, la fillette s’enfuit dans les rues où des dizaines d’ombres prennent vie, mais une grande étendue d’eau bloque maintenant le chemin du retour. Un grand bateau lumineux aborde et débarque des centaines de kami et yōkai tandis que Chihiro s’aperçoit qu’elle devient transparente. Elle part se blottir dans un coin où le jeune garçon la retrouve ; il la force à avaler un peu de nourriture du monde des esprits pour lui éviter de disparaître et la cache de la vue du Yu-bird, un rapace à tête de sorcière, qui patrouille. Il l’emmène ensuite traverser le pont qui mène au palais, tentant de la cacher des esprits et du personnel. Se présentant comme Haku, il semble connaître Chihiro de longue date, et lui conseille de descendre trouver Kamaji, le chauffagiste, pour trouver du travail. Ainsi, la sorcière tenancière des lieux, Yubaba, ne pourra plus la transformer en animal.

      Après avoir descendu plusieurs escaliers vertigineux, Chihiro se retrouve dans la salle des chaudières où travaille Kamaji, un vieil homme à six bras extensibles, accompagné de noiraudes qui transportent le charbon. Elle demande au chauffagiste s’il peut lui donner du travail, mais ce dernier, qui a la charge de préparer les sels de bain et d’envoyer l’eau chaude, lui dit ne pas avoir besoin d’aide supplémentaire. La présentant comme sa petite-fille, il la confie à une jeune femme qui lui apporte à manger pour qu’elle la présente à Yubaba. Après avoir pris plusieurs ascenseurs, Chihiro se retrouve seule au dernier étage du palais, sa compagne ayant dû rester plus bas pour reprendre son travail. Une série de portes et de couloirs la mène au bureau où la sorcière l’attend. Yubaba interroge la fillette pour savoir qui l’a aidée à parvenir jusqu’ici, mais cette dernière se borne à lui demander du travail. Alors que la sorcière tente de l’intimider pour la faire renoncer, Bô, son bébé géant, se réveille et fait du raffut, ce qui donne à Chihiro l’occasion de se faire promettre d’être embauchée. Une fois le contrat signé, Yubaba vole les trois kanjis de son nom et la renomme Sen (千) ; elle appelle Haku, qui s’avère être son apprenti, et lui demande de la superviser. Ce dernier, qui apparaît maintenant froid et autoritaire, la confie comme assistante à Lin, la jeune femme qui l’a accompagnée voir la sorcière. Cette dernière accepte de mauvaise grâce de la prendre sous son aile, mais s’avère rapidement amicale envers la fillette, l’amenant au dortoir et lui fournissant ses nouveaux vêtements de travail.
      Cosplay du Sans-Visage.
      
      Au petit matin, Haku réveille Sen et lui donne rendez-vous pour l’amener voir ses parents ; en traversant le pont, la fillette croise un Sans-Visage qui semble s’intéresser à elle. Redevenu amical, le jeune apprenti l’amène à la porcherie, mais Akio et Yuko Ogino sont maintenant de simples cochons sans aucun souvenir de leur vie humaine. Sen leur promet de revenir les sauver et s’enfuit en larmes. Haku la console et lui rend ses anciens vêtements ainsi que la carte d’adieu écrite par les camarades de son ancienne école. Surprise, elle y lit son ancien prénom qu’elle avait déjà oublié. Son compagnon lui explique que Yubaba contrôle les gens en volant leurs prénoms et qu’elle doit conserver celui-ci en secret ; lui-même ne peut s’enfuir, ayant perdu la mémoire et oublié le sien, mais se souvient étrangement de Chihiro. Avant de retourner finir sa nuit dans la chaufferie, Sen voit un dragon s’envoler au loin.
      
      Alors que la première journée de travail commence, Sen et Lin reçoivent l’ordre de s’occuper du grand bain, très encrassé car réservé aux invités les plus sales. Au cours de son ouvrage, voyant le Sans-Visage dehors sous la pluie, la fillette le laisse entrer. Ce dernier, utilisant sa capacité à se rendre invisible, l’aide à obtenir une plaquette à envoyer à la chaufferie pour faire couler un bain aux herbes, que le contremaître ne voulait pas lui donner, afin de faciliter leur travail de nettoyage. Alors que Lin est partie chercher le déjeuner, il réapparaît et lui tend plusieurs autres plaquettes qu’il a volés, avant de disparaître. Peu après, Yubaba et tous les employés sont en effervescence : un esprit putride se dirige vers le palais, répandant une odeur abominable sur son passage. Sen reçoit l’ordre de le mener au grand bain et de s’occuper de lui. La fillette utilise les autres plaquettes pour remplir à nouveau le bain que l’hôte a fait déborder, mais tombe dedans. Elle s’aperçoit alors que quelque chose dépasse du corps de son client, et commence à tirer dessus, bientôt aidée par Lin et tous les autres employés à l’aide d’une corde fournie par Yubaba qui a compris la vraie nature de l’esprit, gardien d’une grande rivière polluée. Celui-ci, libéré de tous les détritus qui l’encombraient, remercie Sen en lui donnant une boulette amère, avant de partir, non sans laisser de nombreuses pépites d’or sur le sol, ce qui ravit la sorcière et ses employés. `,
      images : "/photos/chihiro7.jpg"
    },
    content2 : {
      text : `La nuit venue, un employé grenouille vient voir près du grand bain s’il ne reste pas de pépites oubliées ; le Sans-Visage, capable de faire apparaître des pépites dorées, le piège et l’avale. Utilisant la voix de la grenouille, l’esprit demande ensuite de la nourriture, faisant apparaître de plus en plus de pépites. Pendant ce temps, Sen rêve que la boulette amère permettrait de rendre forme humaine à ses parents, mais qu’elle ne peut plus identifier ceux-ci parmi tous les autres cochons. En se réveillant, elle s’aperçoit que tous les employés sont déjà levés : tout le monde est occupé à préparer et à convoyer des mets au Sans-Visage, devenu monstrueusement gros, et qui réclame de plus en plus de nourriture, jetant des pépites tout autour de lui depuis son bain. Pas intéressée par l’or, la fillette va sur un balcon voir la mer autour du palais qui a encore monté, et remarque le dragon qu’elle avait vu attaqué par des centaines d’oiseaux en papier. Ayant l’intuition que celui-ci est Haku, elle l’appelle pour qu’il vienne se réfugier, et ferme la fenêtre pour bloquer ses assaillants qui repartent, sauf un qui se colle discrètement dans son dos. Alors que le dragon remonte tant bien que mal vers le haut du palais, Sen court chercher de l’aide, et tombe sur le Sans-Visage entouré et acclamé par tous les employés ; il tente de lui donner de l’or, mais elle le repousse poliment, lui disant qu’elle est pressée. Furieux, l’esprit commence à avaler des employés, semant la panique.
      
      Sen parvient à trouver une échelle qui mène aux étages supérieurs, et arrive dans la chambre de Bô, d’où elle entend la sorcière demander à ses minions, trois têtes bondissantes nommées Kashira, de se débarrasser de Haku dont elle n’a plus besoin, avant de repartir. La fillette a juste le temps de se cacher dans un tas de coussins avant que Yubaba ne passe par la chambre pour s’éclipser, mais le bébé s’intéresse à elle et ne veut pas la laisser partir. Parvenant à lui faire peur avec le sang du dragon sur ses mains, elle se précipite pour aider Haku, mais est attaquée par le Yu-bird. L’oiseau de papier dans son dos fait alors apparaître un hologramme de Zeniba, sœur jumelle de Yubaba, qui transforme Bô en grosse souris, le Yu-bird en oisillon et les Kashira en Bô. Elle explique à Sen que Haku lui a volé un artefact magique et s’est condamné avec la protection magique de celui-ci. Le dragon reprend conscience et détruit l’oiseau de papier, faisant disparaître Zeniba, avant de tomber dans une oubliette, la fillette accrochée à son cou. Avec les dernières forces qui lui reste, il les mène à la chaufferie de Kamaji, et Sen lui fait avaler de force une moitié de la boulette amère, ce qui lui fait vomir l’artefact et reprendre forme humaine. Alors que Haku demeure inconscient, Sen décide de partir chez Zeniba pour lui rendre son bien et lui demander de l’aide. Kamaji lui donne des tickets de train et lui indique l’arrêt, l’avertissant que la ligne est à sens unique.
      
      Lin surgit ; Yubaba a découvert que Sen avait laissé entrer le Sans-Visage, qui souhaite la voir. La sorcière ne peut contrôler le monstre, et demande à la fillette, toujours accompagnée de Bô et du Yu-bird transformés qu’elle ne reconnaît pas, de s’en occuper. L’esprit est contrarié de ne pouvoir offrir à celle qu’il voudrait gâter ce dont elle a besoin ; poussé par sa frustration et sa solitude, il s’apprête à dévorer Sen, mais celle-ci lui donne à manger le reste de la boulette amère, ce qui le fait vomir et le rend furieux. Il poursuit la fillette à travers le palais, régurgitant au fur et à mesure tout ce qu’il a avalé, employés compris, et finit par reprendre sa forme d’origine. Sen en profite, avec l’aide de Lin, pour rejoindre la gare en suivant la voie de chemin de fer immergée, pour prendre le train avec ses deux petits compagnons et le Sans-Visage, rasséréné, qui a décidé de venir avec eux. Au palais, Yubaba est furieuse du bazar qui a été mis et de la fuite de Sen ; pour se venger, elle souhaite sacrifier ses parents, mais Haku, qui s’est réveillé, lui apprend que son bébé a été substitué et emmené chez Zeniba. Le jeune garçon lui fait promettre de libérer la fillette et ses parents s’il lui ramène Bô.
      
      Après un long voyage, et alors qu’il fait déjà nuit, Sen arrive à destination avec ses compagnons chez Zeniba qui les accueille. La fillette lui rend l’artefact en s’excusant pour Haku, et la sorcière lui explique que d’après les règles de ce monde, elle ne devra compter que sur elle-même pour sauver le jeune homme et ses parents ; elle lui offre cependant un charme de protection sous la forme d’un élastique à cheveux qu’elle vient de tisser avec l’aide du Sans-Visage, de Bô et du Yu-bird. À l’aube, Haku arrive sous sa forme de dragon, et ils repartent en volant sur son dos, sauf le Sans-Visage qui décide de rester chez Zeniba comme assistant. Pendant le trajet, Sen se souvient que plus jeune, elle était tombée dans une rivière désormais souterraine nommée Kohaku. Elle comprend que le jeune garçon, qu’elle avait l’intuition de connaître depuis longtemps, est en fait l’esprit de cette rivière, qui l’avait alors sauvée en l’amenant dans des eaux peu profondes. En se souvenant de son véritable nom, Haku est désormais libre, et reprend sa forme humaine ; ils volent tous deux main dans la main jusqu’au pont du palais où Yubaba les attend. Une dernière épreuve attend Sen : elle doit retrouver ses parents parmi une douzaine de cochons. Bô reprend sa forme de bébé, et ayant beaucoup gagné en maturité durant son aventure, gronde sa mère en lui demandant de ne pas faire pleurer sa compagne de voyage. Cette dernière accepte l’épreuve et devine, sous les acclamations des employés, que ses parents ne sont pas parmi les cochons présentés. Son contrat de travail se détruit, la libérant de son existence en tant que Sen, et Haku l’accompagne jusqu’à la frontière du domaine de la sorcière où l’eau a maintenant disparu. Les deux enfants se quittent en se promettant de se revoir, et la fillette rejoint ses parents qui l’attendent à l’entrée du tunnel et ne se sont rendu compte de rien. Une fois de retour à leur voiture, ils s’aperçoivent qu’elle est couverte de végétation et de poussière ; Chihiro se demande si ce qu’elle a vécu était bien réel, mais dans ses cheveux, le porte-bonheur de Zeniba jette un éclat.`,
      images : "/photos/chihiro8.jpg",
    },
    video : {
      srcVideo : "https://www.youtube.com/embed/5-cro68n7CE"
    }

  },


  "Mononoke" : {
    illustration : {
      title : "Princesse Mononoke",
      path: "/photos/Mononoke.jpg",
    },
    content1 : {
      text : `L'histoire se déroule dans le Japon médiéval (ère Muromachi). Ashitaka, le prince de la tribu des Emishis, un peuple reclus au nord de Honshū, est frappé d'une malédiction après avoir tué Nago, un dieu sanglier devenu un démon : son bras est animé d'une force surnaturelle mais est rongé par l'entité démoniaque. La chamane du village le dit condamné à mourir et lui conseille de quitter le village afin d'aller chercher à l'ouest la cause de la colère de la nature et l'espoir de trouver la raison de sa malédiction.

      Sur le chemin, Ashitaka sauve Jiko au détour d'un coup de main de la guerre civile qui ravage le pays. Moine vagabond très désireux de lui montrer sa gratitude, ce dernier conseille à Ashitaka de se rendre dans la forêt où vivent les esprits de la forêt, animaux gigantesques et doués de parole. Ashitaka découvre ensuite deux hommes originaires du village des forges, dirigé par Dame Eboshi. Ils ont été blessés lors d'une attaque menée par la déesse louve Moro, qui a elle-même été blessée par Dame Eboshi. Ashitaka aperçoit peu après San, la princesse Mononoké, une humaine élevée par Moro. Ashitaka ramène les deux hommes jusqu'au village des forges et est chaleureusement accueilli par les femmes du village.
      
      Il rencontre Dame Eboshi, issue de la noblesse et qui a pourtant décidé de sauver des femmes de leur ancienne condition, à une époque où les droits humains comme animaux n'étaient pas de mise. Femme forte, elle recueille tous les indigents, tels des lépreux à qui elle confie la tâche délicate de maintenir et améliorer l'artillerie du village. En effet, les habitants tirent leur subsistance du sol de la forêt et produisent du fer afin de pouvoir acheter vivres et autres nécessités loin de chez eux, mais ils doivent déforester pour pouvoir accéder aux minerais, ce qui excède et enrage les dieux de la forêt. Les lépreux fabriquent donc des armes à feu pour lutter contre les esprits de la forêt. Ashitaka apprend ainsi que Dame Eboshi, qui a tiré sur Nago, est responsable de la corruption l'ayant transformé en démon.
      
      Pendant la nuit, San pénètre dans le village pour tenter de tuer Dame Eboshi mais Ashitaka s'interpose entre elles deux et les assomme. Il quitte ensuite le village en emportant San mais est touché par une balle en partant. Quand San se réveille, elle s'apprête à tuer un Ashitaka affaibli mais est déconcertée quand celui-ci lui dit qu'elle est jolie. Elle se décide ensuite à lui faire confiance quand, après l'avoir déposé sur l’îlot central de l'étang de l'esprit de la forêt, le dieu-cerf soigne la blessure du garçon. `,
      images : "/photos/mononoke2.jpg"
    },
    content2 : {
      text : `Dame Eboshi et les villageois repoussent une attaque des samouraïs du seigneur Asano, qui cherche à s'emparer du village et des armes qui y sont produites. Dame Eboshi rencontre ensuite Jiko, qui travaille en réalité pour l'empereur et a été chargé de lui ramener la tête du dieu-cerf, censée accorder l'immortalité. Tous deux décident de s'allier dans cette tâche.

      Les sangliers dirigés par Okkoto attaquent les forces de Jiko et de Dame Eboshi pour sauver la forêt mais ils sont décimés. Okkoto est gravement blessé et San l'emmène jusqu'au dieu-cerf pour qu'il le guérisse mais le vieux sanglier commence déjà à être corrompu et à se transformer en démon comme Nago. San essaie alors de l'arrêter, aidée par Ashitaka et Moro alors que Jiko et Dame Eboshi les suivent.
      
      Le dieu-cerf arrive et libère Okkoto de sa corruption, le privant, ainsi que Moro, de sa vie. Dame Eboshi le décapite peu après d'une balle d'arquebuse. Cet acte transforme le corps du dieu-cerf en une gigantesque forme visqueuse qui ôte la vie de tout ce qui la touche, humains, animaux et arbres. Moro, dans un dernier sursaut, se venge et arrache un bras à Dame Eboshi. Jiko s'empare alors de la tête du dieu-cerf et l'emporte avec ses hommes alors que le corps de celui-ci, métamorphosé, submerge rapidement la totalité de la forêt.
      
      Après une course-poursuite avec Jiko et ses hommes, Ashitaka et San parviennent à récupérer la tête du dieu-cerf et la lui restitue. Ce dernier guérit alors la forêt complètement dévastée ainsi qu'Ashitaka.
      
      San, bien que très attachée à ce dernier, ne peut pardonner aux humains et reste vivre dans la forêt alors qu'Ashitaka décide d'aller vivre au village des forges d'où il pourra souvent aller voir San. Dame Eboshi, en reconnaissance de leurs actions, s'engage à repartir de zéro pour que son village cohabite plus en harmonie avec la forêt, tandis que Jiko, fataliste, pense à prendre sa retraite. `,
      images : "/photos/mononoke3.jpg",
    },
    video : {
      srcVideo : "https://www.youtube.com/embed/4OiMOHRDs14"
    }

  },

  "Chateau" : {
    illustration : {
      title : "Le Château Ambulant",
      path: "/photos/chateau1.jpg",
    },
    content1 : {
      text : `Une jeune fille de dix-huit ans, Sophie, qui travaille dans le magasin de son défunt père, rencontre par hasard un mystérieux sorcier nommé Hauru, lors d'une course poursuite. Hauru la prend alors en sympathie. Cependant la sorcière des Landes, qui est amoureuse de Hauru, devient jalouse de l'attention portée à Sophie par ce dernier. Pour se venger, elle décide de transformer la jeune Sophie en une vieille dame de quatre-vingt-dix ans. Incapable de révéler cette transformation à sa famille, elle s'enferme chez elle, puis s'enfuit.

      Dans les montagnes, elle rencontre un épouvantail enchanté qu'elle surnomme affectueusement Navet. Celui-ci la mène au château ambulant. Une fois à l'intérieur, après avoir fait le constat d'une insalubrité totale, elle fait connaissance avec le démon du feu, Calcifer. Celui-ci fait mouvoir le château et devine que Sophie a été victime d'un sortilège. Il lui propose alors de rompre le sortilège en lieu de quoi Sophie devra l'aider à son tour afin de briser le pacte qui l'unit à Hauru. Le lendemain, Sophie rencontre Hauru et se présente à lui comme la nouvelle femme de ménage. Au fil des jours, elle parvient à s'intégrer à la vie du château et se lie d'amitié avec le petit Marco. Elle découvre également que la porte d'entrée donne sur plusieurs endroits en même temps (dans une ville, sur un port, dans les landes…). Par la suite, Sophie apprend que Hauru est une personne vaniteuse et immature, et que la vengeance de la sorcière des Landes est due au comportement passé d'Hauru envers elle.
      
      À la suite de la disparition du Prince Justin, du pays voisin, Hauru doit servir son roi en l'aidant à gagner la guerre. Cependant, Hauru refuse, craignant que ce ne soit un piège commandité par son mentor, madame Suliman, une puissante magicienne. Il demande ainsi à Sophie d'aller voir madame Suliman, en se faisant passer pour sa mère, au palais du roi afin de lui annoncer son refus. Sur le chemin, Sophie croise la sorcière des Landes et celle-ci l'informe que le sortilège est irréversible, car elle n'a que le pouvoir de jeter des sorts et non de les défaire. Étant donné que madame Suliman est contre l'alliance entre les sorciers et les démons, celle-ci punit la sorcière des Landes et la condamne à revenir à son état originel. Elle apparaît alors comme une vieille dame décrépite. Madame Suliman prévient Sophie que si Hauru ne collabore pas avec le pays il connaîtra le même sort que la sorcière des Landes. Sophie lui rétorquant que Hauru n'est pas un lâche, mais un homme honnête avec de nobles intentions, redevient quelques instants la jeune Sophie. Cependant, elle retrouve vite son apparence de vieille dame lorsque madame Suliman lui fait remarquer, en se moquant, qu'elle est amoureuse d'Hauru. Ce dernier arrive à ce moment pour la sauver, ainsi que la sorcière des Landes et le chien empoté de madame Suliman, Hin. Pour rejoindre le château au plus vite, Hauru donne à Sophie un anneau qui va la guider jusqu'à destination pendant qu'il tentera de faire diversion. Madame Suliman connaissant la vraie identité de Sophie commence à la traquer pour capturer Hauru.
      
      Sophie rêve de Hauru se transformant en oiseau ou en un démon, chassant les troupes aéroportées de la guerre. Mais elle apprend réellement par Calcifer que ce rêve est réalité et que chaque transformation d'oiseau à humain devient plus dure. L'amour que porte Sophie à Hauru ainsi qu'à tous les autres membres du château la ramène de plus en plus fréquemment à son véritable âge. À force de travail le château redevient vivable, ce qui satisfait Hauru. `,
      images : "/photos/chateau2.jpg"
    },
    content2 : {
      text : `Un jour la mère de Sophie, Honey, toujours belle et jeune, lui rend visite, feignant attention et affection. En réalité Honey travaille pour madame Suliman. Elle remet un cadeau à sa fille, qui s'avère être un piège découvert par la sorcière des Landes. Le cadeau est un petit ver espion et avant d'être détruit par Calcifer, il révèle la position du château ambulant. Tandis que les bombes pleuvent sur la ville, madame Suliman envoie des troupes pour capturer Hauru mais il les repousse, tout en arrêtant une bombe qui tombait sur la maison. Calcifer a du mal à digérer le ver et faiblit d'intensité, avant d'être réanimé par Hauru. Puis ce dernier repart, pour tenter de protéger la ville des bombardements. Voulant sauver Hauru, Sophie fait évacuer le château ambulant, y compris Calcifer : le château tombe en ruine. Mais en lui donnant une mèche de cheveux, Sophie donne la force à Calcifer de réassembler une petite partie du château, qui fonce sur la ville pour sauver Hauru. La sorcière des Landes, apercevant alors le cœur de Hauru dans le corps de Calcifer, s'en empare. Mais cette dernière s'enflamme alors et risque de mourir. Pour la sauver, Sophie asperge d'eau la sorcière ainsi que Calcifer qui s'éteint et devient une flamme bleue. Le château n'étant plus uni par la force de Calcifer, il tombe en ruine : séparés de Marco, la sorcière des Landes et Calcifer, Sophie et Hin tombent d'une falaise.

      Sophie réalise alors l'ampleur de son geste : elle a tué Calcifer et, par conséquent, Hauru. Mais au moment où elle cède aux larmes, l'anneau que lui avait donné Hauru se remet à briller lui indiquant à nouveau une destination. Elle arrive devant une porte — celle du château — la franchit et se retrouve à l'époque de l'enfance de Hauru. Elle voit alors les souvenirs de ce dernier : pour sauver la vie de Calcifer, Hauru lui donne son cœur, mais perd la capacité d'aimer. Avant de retourner dans le présent, Sophie demande à Hauru de l'attendre dans le futur.
      
      Revenue au temps présent, Sophie retrouve Hauru et se rend compte qu'il l'a attendue depuis tout ce temps. Elle prend le cœur des mains de la sorcière des Landes et le remet dans la poitrine d'Hauru, brisant ainsi le lien entre le magicien et Calcifer. Celui-ci retourne à sa forme originelle et peut de nouveau voler : il est libre. Le peu d'éléments restant du château, n'étant plus retenus par aucun pouvoir magique, tombent complètement en ruines. Navet, après avoir sauvé la vie de tout le monde, est embrassé par Sophie : il reprend alors forme humaine. On apprend alors que c'est le Prince Justin. Par la suite ayant embrassé Hauru, par amour, Sophie redevient jeune. Le Prince Justin, quant à lui, retourne dans son pays pour mettre un terme à la guerre. Madame Suliman, qui voit la scène à travers les yeux de Hin, décide également d'y mettre fin. Tandis que les bombardiers rentrent de la guerre, un nouveau château, volant, est visible à l'écran, au-dessus des nuages. À son bord, Sophie et Hauru, qui peuvent enfin vivre leur amour, ainsi que Hin, Marco et la Sorcière des Landes ; tous vivent désormais une existence heureuse. `,
      images :  "/photos/chateau3.jpg",
    },
    video : {
      srcVideo : "https://www.youtube.com/embed/pGEsAlY49hw" 
    }

  },

  "Ponyo" : {
    illustration : {
      title : "Ponyo sur la Falaise",
      path: "/photos/Ponyo.jpg",
    },
    content1 : {
      text : `Fujimoto, un sorcier qui a abandonné le monde des humains pour vivre au fond des océans, fait des expériences avec l’« eau de vie », un liquide qui renforce la faune marine ; il espère ainsi un jour bouleverser l’équilibre écologique et voir la mer, maltraitée par les hommes, reprendre sa prééminence. L’aînée de ses filles, Brunehilde, petit poisson rouge de cinq ans à visage humain, profite d’un moment d’inattention de son père pour se glisser à travers un hublot du sous-marin et rejoindre la surface, sous l’ombrelle protectrice d’une méduse. Alors qu’elle découvre émerveillée la nature terrestre, elle voit au loin Sôsuké, un petit garçon de son âge vivant dans une maison sur une falaise, descendre dans la calanque avec son bateau jouet. Soudain, elle est surprise par un chalutier, dont le filet charrie une grande quantité d’ordures, et se retrouve coincée dans un pot de verre.

      Alors qu’il arrive près de l’eau, Sôsuké remarque le pot et se blesse au doigt en le brisant pour libérer son occupante, qui lèche le sang perlant de la coupure. Le petit garçon, appelé par sa mère, Lisa, remonte vers sa maison, tandis que des yōkai marins en forme de vagues, au service de Fujimoto, tentent en vain de récupérer Brunehilde. Sôsuké remplit un seau d’eau et y met sa trouvaille, qui lui crache un jet d’eau à la figure ; heureux de voir qu’elle est encore vivante, le garçonnet décide de la protéger, et l’emporte avec lui dans la voiture, où sa mère l’attend pour aller à la maternelle. Durant le trajet, il remarque que sa coupure a disparu, et décide d’appeler sa nouvelle amie Ponyo ; il tente de lui donner du pain de son sandwich, mais cette dernière préfère voler le jambon, qu’elle dévore goulument. Fujimoto, très ennuyé que sa fille ait été enlevée par un humain, tente de suivre la voiture le long de la côte, mais est confronté aux ordures qui jonchent la mer à proximité du port.
      
      Sôsuké et Lisa arrivent à la maison de retraite des Tournesols, qui jouxte le jardin d’enfants. Le garçonnet cache le seau sous un buisson et va saluer sa maîtresse ; ses petites camarades tentent de l’entraîner pour aller jouer, mais il préfère retourner voir sa protégée le plus vite possible. Surpris par Kumiko, une petite fille qui semble lui porter beaucoup d’attentions, Sôsuké lui montre le contenu du seau, mais la fillette se moque de Ponyo, qui l’arrose. Le petit garçon fuit alors les pleurs de sa camarade avec son seau, du côté de l’hospice où travaille sa mère ; il montre son amie aux vieilles dames en fauteuil roulant, Yoshi et Noriko qui attendent toujours avec impatience les visites du garçonnet qui égaient leur quotidien monotone, et Toki, qui est terrifiée par le poisson à visage humain qui annoncerait selon elle un tsunami. Ponyo arrose la vieille dame, dont les cris font fuir à nouveau Sôsuké, qui se réfugie sous la digue du port. Alors que la petite créature se met à parler, disant son nom, celui de son ami et le mot « aime » (好き, suki?), Fujimoto profite du fait que le petit garçon soit isolé et à proximité de la mer pour envoyer ses esprits marins le submerger et récupérer sa fille. Désespéré, le garçonnet se précipite dans la mer à la recherche de son amie au risque de se noyer, et est récupéré en larmes par sa mère.
      
      De retour à la maison, Sôsuké est très abattu ; le soir venu, il guette le Koganei Maru, cargo sur lequel son père est capitaine, pour échanger avec lui des signaux lumineux en morse. Kôichi aurait dû être de passage pour le dîner, mais n'a finalement pas pu venir, provoquant la colère et le chagrin de Lisa, que le petit garçon console. Dans sa demeure, creusée dans un rocher au fond de l’océan, Fujimoto fait la leçon à Brunehilde, mais cette dernière lui déclare qu’elle s’appelle « Ponyo », et veut devenir humaine pour retrouver Sôsuké. Alors que son père lui brosse un portrait peu flatteur des hommes, qui polluent les océans, elle persiste à souhaiter avoir des mains et des pieds, et prend une forme hybride en se faisant pousser des bras et des jambes à trois doigts. Fujimoto comprend alors qu’elle a ingéré du sang humain, et utilise son pouvoir pour la ramener à sa forme initiale. `,
      images : "/photos/ponyo3.jpg"
    },
    content2 : {
      text : `Alors que le sorcier sort, Ponyo est libérée par ses sœurs de la bulle où elle était maintenue prisonnière, et fait repousser ses membres. Décidant de partir à la recherche de son ami, elle submerge le repaire de Fujimoto et libère l’énergie du puits d’eau de vie, ce qui lui permet d’achever sa transformation en petite fille. Chevauchant un banc de poissons, elle jaillit à la surface, provoquant un typhon, qui manque de faire chavirer le Koganei Maru. Au Tournesols, Sôsuké dit au revoir à sa maîtresse et rejoint sa mère à l’hospice, où il offre des origamis aux vieilles dames. Lisa l’emmène en voiture, et ils partent sous la pluie battante, mais le trajet se transforme en une course contre la mer démontée, sur laquelle le garçonnet voit une petite fille courir. Alors qu’ils se garent chez eux, Ponyo surgit des vagues et se jette dans les bras de Sôsuké ; celui-ci ne reconnaît pas son amie au premier abord, mais finit par comprendre qui elle est. Lisa coupe court aux retrouvailles pour emmener les deux enfants à l’abri dans la maison. Après les avoir séchés et nourris, la jeune femme, qui s’inquiète pour les occupants des Tournesols, profite d’une accalmie provoquée par l’assoupissement de Ponyo pour retourner à l’hospice, laissant Sôsuké garder la maison.

      Au large, durant la nuit, le Koganei Maru est en perdition, les marins voyant au loin les lumières de tous les autres navires en panne également ; soudain, Gran Mamare, divinité de la mer et mère de Brunehilde, passe à la surface de l’eau, et les turbines se remettent en route. Fujimoto tente de s’approcher de la maison où Sôsuké et Ponyo dorment, mais est repoussé par un sortilège d’exclusion posé par sa fille, qu’il ne peut qu’apercevoir par la fenêtre ; la divinité de la mer arrive, et s’entretient avec le sorcier. Celui-ci est terrifié par les événements provoqués par Brunehilde, devenue humaine : la mer est revenue à l’époque du Dévonien (deux Dunkleosteus apparaissent dans un court passage), la lune se rapproche de la Terre, et les satellites artificiels commencent à tomber, pour se consumer dans l’atmosphère, mais Gran Mamare le rassure en lui rappelant la magie ancienne selon laquelle une sirène peut perdre ses pouvoirs et devenir une femme, si le cœur de l’homme qu’elle aime ne faiblit pas ; dans le cas contraire, elle est transformée en écume.
      
      Le lendemain, les deux enfants se réveillent ; le niveau de la mer, qui foisonne de poissons disparus depuis des centaines de millions d’années, est monté jusqu’au seuil de la maison. Avec ses pouvoirs, Ponyo élargit le bateau jouet de Sôsuké, et les deux enfants montent à bord avec des provisions ; mettant en route le moteur pop-pop, ils suivent la route submergée. Croisant un couple avec leur bébé sur une barque, ils leur offrent de la soupe et des sandwichs et récupèrent une bougie de rechange ; ils voient ensuite tous les gens du village passer sur une file de bateaux à rames, mais personne n’ayant vu Lisa, ils poursuivent leur route. Lorsque la bougie initiale finit de se consumer, Sôsuké demande à Ponyo d’agrandir la nouvelle, mais la petite fille tombe de sommeil ; le garçonnet se met donc à l’eau pour pousser le bateau à la nage. Ils finissent par arriver à un endroit où la route émerge, alors que le bateau jouet reprend sa taille normale, et le garçon affolé retrouve la voiture de Lisa sans son occupante. Le prenant par la main, son amie lui redonne du courage, et ils poursuivent leur route à pied.
      
      Aux Tournesols, les habitations submergées sont protégées par une énorme bulle, et Lisa discute en privé avec Gran Mamare. Fujimoto rassemble les vieilles dames, qui ont retrouvé l’usage de leurs jambes, pour les prévenir que Sôsuké et Ponyo sont en route et qu’elles vont être les témoins de leur épreuve. Suivant la route, les deux enfants arrivent à l’entrée d’un tunnel, et alors qu’ils le traversent, la petite fille reprend sa forme de poisson, ne donnant plus signe de vie. Le garçonnet, affolé, la remet dans son seau et tente de lui faire reprendre conscience, lorsque Fujimoto apparaît et lui dit de la laisser dormir et de l’accompagner pour retrouver Lisa et les vieilles dames. Alors que Sôsuké ne lui fait pas confiance, et tente de rejoindre la vieille Toki qui n’a pas voulu le croire non plus, le sorcier envoie ses esprits marins pour les submerger, et les convoie jusqu’aux Tournesols, où le petit garçon s’entretient avec Gran Mamare. Alors qu’il affirme accepter son amie telle qu’elle est et l’aimer quelle que soit sa forme, et que cette dernière accepte de renoncer à ses pouvoirs pour grandir et vivre auprès de son ami, les réactions en chaîne cataclysmiques s’interrompent, et tout le monde est ramené à la surface. Tandis que Fujimoto s’excuse et serre la main de Sôsuké, Ponyo saute du seau et embrasse son ami, reprenant sa forme de petite fille ; les bateaux des marins, dont celui de Kôichi, et les barques des gens du village accostent, et tout le monde se retrouve. `,
      images : "/photos/ponyo2.jpg",
    },
    video : {
      srcVideo : "https://www.youtube.com/embed/YTrEECZhpL0" 
    }
  },

  "Terremer" : {
    illustration : {
      title : "Les contes de Terremer",
      path: "/photos/terremer.jpg",
    },
    content1 : {
      text : `L'histoire se déroule à Terremer, un monde imaginaire peuplé d'êtres humains et de dragons.

      Le prince Arren, un adolescent en quête d'identité, fuit son château et erre dans la campagne après avoir tué son père. Il rencontrera Épervier, Teru ainsi qu'un terrible sorcier. Arren découvre comment dépasser ses peurs et s'affirmer. `,
      images : "/photos/terremer3.jpg"
    },
    content2 : {
      text : `Autour du film                                                                                                           :

      Sur son site web, Ursula K. le Guin a exprimé une réaction mitigée à l'égard de cette adaptation animée, dont elle espérait pourtant beaucoup3.

      Elle y explique notamment comment, vers 1984, elle avait refusé une première offre de Hayao Miyazaki, qui venait de terminer Nausicaä (dont les capacités de l’héroïne à comprendre le vent sont en partie inspirées du cycle Terremer), mais dont elle ne connaissait pas encore l'œuvre. Ce n'est qu'en 1999, à la suite de sa découverte tardive de Totoro, qu'elle tomba sous le charme du réalisateur japonais et reprit contact avec lui pour rediscuter les termes d'une adaptation cinématographique de Terremer.
      
      Lors d'une entrevue avec Miyazaki en 2005, Le Guin apprit avec désarroi que ce dernier (qui se disait alors proche de la retraite et cherchait désespérément un successeur) avait l'intention de confier la réalisation du film à son fils Gorō, tout en assurant à l'écrivaine qu'il en superviserait la production. Miyazaki père n'eut pourtant aucun rôle dans cette adaptation et fut souvent en désaccord avec les choix de son fils4.
      
      Ursula K. Le Guin regrette que ces rapports tendus aient vraisemblablement nui à l'intérêt du film, dont elle apprécie globalement les qualités visuelles mais qui n'est cependant pas fidèle à l'esprit de son univers. Elle dit ainsi à Gorō : « Ce n'est pas mon livre. C'est votre film. C'est un bon film. »`,
      images : "/photos/ursula.jpg",
    },
    video : {
      srcVideo : "https://www.youtube.com/embed/-T1iFyyL42M"
    }
}
}


module.exports=movies;
